name: Backend CI

on:
  push:
    branches:
      - master
      - feature/*


  pull_request:
    branches:
      - master
      - feature/*


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Restore Packages
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore
        

    